{
 "title": "Spark-CPU",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "executorProcessUuid",
    "query": "select  distinct \"processUuid\" from \"metrics\".\"autogen\".\"CpuAndMemory\" where \"role\" = 'executor'  AND $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Driver CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CpuAndMemory",
     "query": "select \"gc-Copy-collectionTime\" as Copy, \"gc-MarkSweepCompact-collectionTime\" as  MarkSweepCompact from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND $timeFilter",
     "select": [
      [
       { "params": [ "processCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exec Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-CodeCache-usageUsed\" as CodeCache, \"memoryPools-CompressedClassSpace-usageUsed\" as  CompressedClassSpace, \"memoryPools-Metaspace-usageUsed\" as  Metaspace from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"gc-Copy-collectionTime\" as Copy, \"gc-MarkSweepCompact-collectionTime\" as  MarkSweepCompact from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executors CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_processUuid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CpuAndMemory",
     "query": "SELECT mean(\"processCpuLoad\") FROM \"CpuAndMemory\" WHERE \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter GROUP BY time($__interval),processUuid fill(null)",
     "select": [
      [
       { "params": [ "processCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executors CPU Detailed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_processUuid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IO",
     "query": "SELECT DIFFERENCE(mean(\"stat-idle-1\")) FROM \"IO\" WHERE \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter GROUP BY processUuid,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "stat-idle-1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-EdenSpace-usageUsed\" as EdenSpace, \"memoryPools-SurvivorSpace-usageUsed\" as  SurvivorSpace, \"memoryPools-TenuredGen-usageUsed\" as  TenuredGen from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"role\"='driver' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-EdenSpace-usageUsed\" as EdenSpace, \"memoryPools-SurvivorSpace-usageUsed\" as  SurvivorSpace, \"memoryPools-TenuredGen-usageUsed\" as  TenuredGen from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"memoryPools-CodeCache-usageUsed\" as CodeCache, \"memoryPools-CompressedClassSpace-usageUsed\" as  CompressedClassSpace, \"memoryPools-Metaspace-usageUsed\" as  Metaspace from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Committed And Used Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where   \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Committed and Used Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"heapMemoryCommitted\" as Committed, \"heapMemoryTotalUsed\" as Used from \"metrics\".\"autogen\".\"CpuAndMemory\"  where  \"role\" = 'driver' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Direct Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"bufferPools-direct-memoryUsed\" as Used, \"bufferPools-direct-totalCapacity\" as  Capacity from \"metrics\".\"autogen\".\"CpuAndMemory\"  where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " select  /^stat-idle.*/,/^stat-iowait.*/,/^stat-nice.*/,/^stat-system.*/,/^stat-user.*/ from \"metrics\".\"autogen\".\"IO\" where \"processUuid\" =~ /^$executorProcessUuid$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Threads",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  \"host\", \"threadName\", \"threadState\"  from \"metrics\".\"autogen\".\"Stacktrace\" where \"processUuid\" =~ /^$executorProcessUuid$/ AND (\"threadState\" = 'WAITING' OR \"threadState\" = 'BLOCKED' ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}